config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'artists#index'

  resources :photos

  resources :artists, only: [:index] do
    resources :songs, only: [:index, :create, :destroy] do
      collection do
      get :by_name
      get :by_created_at
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  has_many :photos

  scope :by_name,     -> {order(:name)}
  scope :created_at,   -> { order(:created_at) }

  def self.order_by_name
      order(:name)
  end

  def self.order_by_created_at
      order(:created_at)
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader



end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @songs = @artist.songs.find(params[:id])
  end




#--- sorting filters ---
  def by_name
    @artists = Artist.by_name
    render action: :index
  end

  def by_created_at
    @artists = Artist.created_at
    render action: :index
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController



end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist

  def index
    @song = Song.new
    @songs = @artist.songs
  end

  def create
    song = @artist.songs.build(song_params)

    if song.save
      render status: 200, json: {
        message: "Song successfully added",
        song: song
      }.to_json
    else
      render status: 422, json: {
        error: song.errors.full_messages
      }.to_sjon
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy!

    @songs = @artist.songs

    respond_to do |format|
      format.html { redirecto_to artist_songs_path(@artist) }
      format.js
    end
  end

  private
    def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def song_params
      params.require(:song).permit(:title, :album, :year)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1>Songs</h1>

<%= form_for Song.new do |f| %>
  <div class="form-group">
    <%= f.text_field :title, placeholder: "Title" %>
  </div>

  <div class="form-group">
  <%= f.submit %>
  </div>
<% end %>

app/views/artists/index.html.erb
<div class="filteritem">
     <%# link_to "Sort by name", by_name_song_artists_path %>
   </div>
   <div class="filteritem">
        <%# link_to "Sort by time", by_created_at_artists_path %>
      </div>

      <ul>
         <% @artists.each do |artist| %>
         <% @artist = artist %>
         <li><%= link_to artist.name, artist_songs_path(artist) %></li>             <% @artist.photos.each do |photo| %>
             <%= image_tag photo.image.thumbnail %>
             <% end %>
           </li>
         <% end %>
         </ul>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<center id="notice"><%= notice %></center>

  <%= render "form" %>

  <ul>
    <%= render @songs %>
  </ul>

<%= link_to "Go to all artists", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Songdb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for [@artist, song] do |f| %>
  <%= f.text_field :title, placeholder: "Song name", id: "song-name", data: { artist_id: artist.id } %>
  <ul id="errors"></ul>
<% end %>

app/views/songs/_song.html.erb
<li id="song-<%= song.id %>">
  <%= song.title %>
  <%= link_to "Delete", artist_song_path(@artist, song), method: :delete, remote: true %>
</li>

app/views/songs/destroy.js.erb
$("#songs").html("<%= j render @songs, artist: @artist %>");

app/views/songs/index.html.erb
<h1><%= @artist.name %></h1>

<ul id="songs">
  <%= render @songs, artist: @artist %>
</ul>

<%= render "form", song: @song, artist: @artist %>
<br>
<br>
<hr>